PREFIX foi: <http://publishmydata.com/def/ontology/foi/>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?code 
WHERE
{
	VALUES ?value
	{ 
	<http://statistics.gov.scot/def/foi/collection/council-areas>
	<http://statistics.gov.scot/def/foi/collection/countries>
	}

 ?s foi:memberOf ?value ;
    rdf:label ?name ;
    foi:code ?code ;
    <http://statistics.data.gov.uk/def/statistical-geography#status> ?status .

FILTER (?status = "Live")

}
