PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foi: <http://publishmydata.com/def/ontology/foi/>

SELECT ?Year ?AreaName ?Qualification ?Figure
	WHERE {
		VALUES ?places { <http://statistics.gov.scot/def/foi/collection/council-areas> <http://statistics.gov.scot/def/foi/collection/countries>}
	
                    ?obs <http://purl.org/linked-data/cube#dataSet> <http://statistics.gov.scot/data/qualifications-working-age-people>; ## Getting to the dataset
                    <http://statistics.gov.scot/def/measure-properties/count> ?Figure;  ##Getting the Count Data for Economic Activity
                    <http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?Area; ## Getting the Area Names
                    <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?Year1;  ## Getting the Year Information 
                    <http://statistics.gov.scot/def/dimension/qualification> ?qual1. ## Getting qualification information
 					
  					?Area foi:memberOf ?places .
                   
                    ?Area rdfs:label ?AreaName.
                    ?Year1 rdfs:label ?Year.
                    ?qual1 rdfs:label ?Qualification.                    
                  }
                    
ORDER BY ?Year ?AreaName ?Qualification  ## Ordering the table
